// 指定版本

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.14.0
// source: M1.proto

package myproto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// 请求消息格式
type M1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId   uint64 `protobuf:"varint,3,opt,name=userId,proto3" json:"userId,omitempty"`
	DeviceId string `protobuf:"bytes,4,opt,name=deviceId,proto3" json:"deviceId,omitempty"`
	From     int64  `protobuf:"varint,5,opt,name=from,proto3" json:"from,omitempty"`
	Limit    int64  `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`
	Scene    string `protobuf:"bytes,7,opt,name=scene,proto3" json:"scene,omitempty"`
	Action   string `protobuf:"bytes,8,opt,name=action,proto3" json:"action,omitempty"`
}

func (x *M1) Reset() {
	*x = M1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_M1_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *M1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*M1) ProtoMessage() {}

func (x *M1) ProtoReflect() protoreflect.Message {
	mi := &file_M1_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use M1.ProtoReflect.Descriptor instead.
func (*M1) Descriptor() ([]byte, []int) {
	return file_M1_proto_rawDescGZIP(), []int{0}
}

func (x *M1) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *M1) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *M1) GetFrom() int64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *M1) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *M1) GetScene() string {
	if x != nil {
		return x.Scene
	}
	return ""
}

func (x *M1) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

var File_M1_proto protoreflect.FileDescriptor

var file_M1_proto_rawDesc = []byte{
	0x0a, 0x08, 0x4d, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x6d, 0x31, 0x22, 0x90,
	0x01, 0x0a, 0x02, 0x4d, 0x31, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a,
	0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f,
	0x6d, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x14, 0x0a,
	0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x69,
	0x6d, 0x69, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x3b, 0x6d, 0x79, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_M1_proto_rawDescOnce sync.Once
	file_M1_proto_rawDescData = file_M1_proto_rawDesc
)

func file_M1_proto_rawDescGZIP() []byte {
	file_M1_proto_rawDescOnce.Do(func() {
		file_M1_proto_rawDescData = protoimpl.X.CompressGZIP(file_M1_proto_rawDescData)
	})
	return file_M1_proto_rawDescData
}

var file_M1_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_M1_proto_goTypes = []interface{}{
	(*M1)(nil), // 0: m1.M1
}
var file_M1_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_M1_proto_init() }
func file_M1_proto_init() {
	if File_M1_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_M1_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*M1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_M1_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_M1_proto_goTypes,
		DependencyIndexes: file_M1_proto_depIdxs,
		MessageInfos:      file_M1_proto_msgTypes,
	}.Build()
	File_M1_proto = out.File
	file_M1_proto_rawDesc = nil
	file_M1_proto_goTypes = nil
	file_M1_proto_depIdxs = nil
}
